version: 2.1 
general:

jobs:
  test:

    working_directory: ~/repo 

    docker:
    - image: circleci/openjdk:8-jdk

    environment:
      # Customize the JVM maximum heap size
      JVM_OPTS: -Xmx3200m
            
    steps:
      - checkout

      # download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # use latest cache if no exact match found
            - v1-dependencies-

      - run:
          name: run unit tests 
          command: mvn clean test

      # save build cache
      - save_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2 
    
      #- store_test_results:
        #  path: ~/repo/target/scala-maven-example-1.0.0-SNAPSHOT.jar 

      # check code quality
      - run:
          name: Install Sonarqube scanner
          command: |

             wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip
             unzip sonar-scanner-cli-3.2.0.1227-linux.zip

#      - run:
#          name: Run Sonarqube scanner
#          command: |
#                 export SONAR_SCANNER_OPTS="-Xmx512m"
#                 eval ./sonar-scanner-3.2.0.1227-linux/bin/sonar-scanner \
#                 -Dsonar.projectKey=scala-maven-example \
#                -Dsonar.sources=. \
#                 -Dsonar.host.url=${SONAR_SERVER} \
#                 -Dsonar.login=${SONARQUBE_TOKEN} $SONAR_SCANNER_OPTS_CUSTOM

  build:
    
    working_directory: ~/repo 

    docker:
    - image: circleci/openjdk:8-jdk

    environment:
      # Customize the JVM maximum heap size
      JVM_OPTS: -Xmx3200m
            
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # use latest cache if no exact match found
            - v1-dependencies-
 
      - run: 
          name: create package
          command: mvn clean install -Dmaven.test.skip=true

      # store artifacts
      - store_artifacts:
          path: ~/repo/target/scala-maven-example-1.0.0-SNAPSHOT.jar
      
      # save build cache
      - save_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}  
          paths:
            - ~/.m2
            
      # create workspace
      - run:
          name: Workspace
          command: |
            mkdir -p workspace
            pwd
            ls -lart ~/repo/target
            cp ~/repo/target/scala-maven-example-1.0.0-SNAPSHOT.jar ~/repo/workspace/scala-maven-example-1.0.0-SNAPSHOT.jar
            cp ~/repo/Dockerfile ~/repo/workspace
            
      #- persist_to_workspace:
      #    root: workspace
      #    paths:
      #      - scala-maven-example-1.0.0-SNAPSHOT.jar
      #      - Dockerfile
            
 # push: 
    
 #   working_directory: ~/repo 

#    docker:
#    - image: circleci/python:3.6.1

#    environment:
      # Customize the JVM maximum heap size
#      JVM_OPTS: -Xmx3200m
            
 #   steps:
 #     - checkout
      
 #     - attach_workspace:
 #         at: workspace
      
      - run:
          name: install python and awscli
          command: |
            sudo apt-get update && sudo apt-get install -qq -y python-pip libpython-dev
            curl -O https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
            sudo pip install -q awscli --upgrade
            aws --version      
            
      # setup remote env for docker
      - setup_remote_docker
              # docker_layer_caching: true
      
 #     - restore_cache:
 #         keys:
 #           - v1-dependencies-{{ checksum "pom.xml" }}
            # use latest cache if no exact match found
#            - v1-dependencies-
            
#      # install aws cli
#      - run:
#          name: install aws cli
#          command: |
#             python3 -m venv venv
#             . venv/bin/activate
#             pip install awscli
             
#      - run:
#          name: Setup common environment variables
#          command: |
#            echo 'export ECR_REPOSITORY_NAME="${AWS_RESOURCE_NAME_PREFIX}"' >> $BASH_ENV
#            echo 'export FULL_IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:${CIRCLE_SHA1}"' >> $BASH_ENV
      
      - run:
          name: Build image
          command: |
            docker build -t circleci/scala-maven .
            
      #- run:
      #    name: Save image to an archive
      #    command: |
      #      mkdir docker-image
      #      docker save -o docker-image/image.tar $FULL_IMAGE_NAME
          
      # build docker image
      #- run:
      #    name: Docker build
      #    command: |
      #      pwd
      #      ls -altr
      #      cd ~/repo/workspace
      #      ls -latr ~/repo/workspace
      #      docker build -t circleci/scala-maven .
            
      # pushing to ECR
      - run:
          name: Push to ECR
          command: |
            . venv/bin/activate
            eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$CIRCLE_SHA1
                   
      # show all docker images
      - run: 
          name: 
          command: | 
            eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
            aws ecr list-images --repository-name scala-maven
      
workflows:
  version: 2.1
  test-and-build:
    jobs:
    - test
    - build:
        requires:
          - test
    #- push:
    #    requires:
    #      - build
        filters:
          branches:
            only:
            - master
            - develop
